apiVersion: v1
kind: Service
metadata:
  name: local-redis
spec:
  selector:
    app: local-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-redis
  template:
    metadata:
      labels:
        app: local-redis
    spec:
      containers:
      - name: local-redis
        image: redis:7.4-bookworm
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
