ARG BASE_IMAGE=mcr.microsoft.com/dotnet/sdk:8.0.402-bookworm-slim

FROM ${BASE_IMAGE}
ARG PROJECT_NAME
RUN mkdir -p /sln
WORKDIR /sln
COPY . .
RUN dotnet restore
RUN dotnet build --no-restore -c Release
